### ISSUE TITLE
resources to learn more about ECS

### ISSUE THREAD

**Issue by moskittle** [SanderMertens/ecs-faq#1]
Thanks for sharing.

I am not able to access the link [Blog explaining how to build a simple ECS](https://blog.therocode.net/2018/08/simplest-entity-component-system) under the question [**Where can I find resources to learn more about ECS?**](https://github.com/SanderMertens/ecs-faq#where-can-i-find-resources-to-learn-more-about-ecs)
I am not sure if the link is not valid anymore or the firewall in my region is blocking it.  

Anyway, I found a relative equivalent article about building a simple ECS. I am still reading it and think it might be helpful to be added.
Here's the [link](https://austinmorlan.com/posts/entity_component_system/#demo).

**Comment by SanderMertens** [comment]
Thanks for letting me know, that link appears to be dead. Also nice article! I'll add it to the list.
