### ISSUE TITLE
Pls add `tinyecs` to python implementations

### ISSUE THREAD

**Issue by DickerDackel** [SanderMertens/ecs-faq#22]
...shameless plug...

It's available on pypi to `pip install tinyecs`
github is here: https://github.com/dickerdackel/tinyecs

tinyecs is a non-OO, singleton approach, in contrast to the established Esper.
In its current iteration, it has now evolved into the category of Archetype ECS.

thx - Michael

**Comment by SanderMertens** [comment]
I only include ECS frameworks that have reached some level of adoption (at least ~100 stars), feel free to reach out again once your implementation has achieved that!
