### ISSUE TITLE
Framework Suggestion

### ISSUE THREAD

**Issue by guipaz** [SanderMertens/ecs-faq#26]
Hi! Thank you for this thorough FAQ. I'm reading it over and over as I implement my ECS solution.

I'd like to suggest an addition for the framework list: [Bang](https://github.com/isadorasophia/bang), an ECS framework in C#. I've learned a lot from their code and sample project.

Thank you again and I hope this suggestion helps.

**Comment by SanderMertens** [comment]
Added it, thanks for the suggestion!
